[programs.localnet]
solana_twitter = "9dR6c95cjzNhS4rnhzgZpRAhUmVrNq5w6oHyPs5bqAev"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/aoikurokawa/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello, World!'"
